name: Build and Publish Docker Image

on:
  push:
    tags:
        - 'v*.*.*'

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        environment: Prod
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4
            
            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v4
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract tag name
              id: vars
              run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

            - name: Build and push image
              uses: docker/build-push-action@v7
              with:
                context: ./backend
                file: ./backend/Dockerfile
                push: true
                tags: |
                  ghcr.io/${{ github.repository_owner }}/supporthub:${{ steps.vars.outputs.TAG_NAME }}
                  ghcr.io/${{ github.repository_owner }}/supporthub:latest

            - name: Trigger Render deploy
              run: curl -fsS -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"